FROM fodaveg/develop-box:t5
# COPY ./public-html/ /usr/local/apache2/htdocs/

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

RUN echo "IdentityFile vhost" >> /etc/apache2/sites-available/000-default.conf

# Main attributes for running the container
WORKDIR /srv/citope
EXPOSE 80
