FROM httpd:2.4
# COPY ./public-html/ /usr/local/apache2/htdocs/

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

RUN echo "IdentityFile vhost" >> /etc/apache2/sites-available/000-default.conf


# RUN ansible-playbook utils/ansible/playbook-apache.yml -c local

EXPOSE 80

CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]
